---
- name: Install Applications
  hosts: all
  tasks:
          - name: Install IIS Web-Server with sub features and management tools
            win_feature:
                    name: Web-Server
                    state: latest
                    include_sub_features: yes
                    include_management_tools: yes
            register: win_feature
     
          - name: Install Git
            win_chocolatey:
                    name: git
                    state: latest

          - name: Instal VsCode
            win_chocolatey:
                    name: vscode
                    state: latest

          - name: Install SumatraPDF
            win_chocolatey:
                    name: sumatrapdf
                    state: latest


- name: Users & Groups Configuration
  hosts: all
  tasks:                    

          - name: Create service user
            win_user:
                    name: svc_marte_user
                    password: p@ssw0rd!
                    state: latest
                    groups:
                            - Users
                            - Administrators
                            - IIS_IUSRS
          
          - name: Add IIS_IUSRS allow rights
            win_acl:
                    path: C:\inetpub\wwwroot
                    user: IIS_IUSRS
                    rights: FullControl
                    type: allow
                    state: latest
                    inherit: ContainerInherit, ObjectInherit
                    propagation: 'None'


- name: Rights Configuration
  hosts: all
  tasks:    
          - name: Add IIS_IUSRS allow rights
            win_acl:
                    path: C:\inetpub\wwwroot
                    user: IIS_IUSRS
                    rights: FullControl
                    type: allow
                    state: latest
                    inherit: ContainerInherit, ObjectInherit
                    propagation: 'None'                

          - name: Add program files allow rights
            win_acl:
                    path: "{{ item }}"
                    user: svc_marte_user
                    rights: FullControl
                    type: allow
                    state: latest
                    inherit: ContainerInherit, ObjectInherit
                    propagation: 'None'
            with_items:
                  - C:\Program Files
                  - C:\Program Files (x86)

- name: Prerequesits
  hosts: all
  tasks: 
          - name: Install .Net Framework
            win_chocolatey:
                    name: dotnetfx
                    state: latest

          - name: Install .Net Core Runtime
            win_chocolatey:
                    name: dotnetcore-runtime
                    state: latest

          - name: 
            win_chocolatey: Install .Net Core Hosting Bundle
                    name: dotnetcore-windowshosting
                    state: latest

          - name: Install Microsoft Visual C++ Redistributable for Visual Studio 2015
            win_chocolatey:
                    name: vcredist2015
                    state: latest
